<a href="https://colab.research.google.com/github/LeeYuuuan/yuanyuansrep/blob/main/cal_mtx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
d1 = []
d2 = []
d3 = []

with open('data.txt', 'r') as f:
    data = f.readlines()
    i = 0
    temp_data_1 = []
    temp_data_2 = []
    temp_data_3 = []

    while i < len(data):

        if data[i]!= "\n":
            temp = data[i][1:-2].split("，")
            temp_data_1.append(float(temp[0]))
            temp_data_2.append(float(temp[1]))
            # print(float(temp[2]))
            temp_data_3.append(float(temp[2]))
            # print(i)
        else:
            d1.append(temp_data_1)
            d2.append(temp_data_2)
            d3.append(temp_data_3)
            temp_data_1 = []
            temp_data_2 = []
            temp_data_3 = []
        i+=1


    # print(data[0][1:-2].split(","))

In [ ]:
with open('data.txt', 'r') as f:
    data = f.readlines()
    print(len(data))

42


### add data

In [ ]:
import numpy as np
mtx = []

with open("data.txt", 'r') as f:
    i = 0
    data = f.readlines()
    temp_data = []
    while i < 4:
        for j in range(4):
            temp_1 = data[i].split("，")
            temp_2 = data[i + 5].split("，")
            temp_3 = data[i + 10].split("，")
            temp_data.append((float(temp_1[j]), float(temp_2[j]), float(temp_3[j])))

        mtx.append(temp_data)
        temp_data = []

        i+=1



In [ ]:
def calculate_P(ai, aj):
    """calculate P(ai > aj)
    """
    if ai[1] >= aj[1]:
        return 1

    if ai[1] < aj[1] and ai[2] > aj[0]:
        return (aj[0] - ai[2]) / ((ai[1] - ai[2]) - (aj[1] - aj[0]))
    else:
        return 0


In [ ]:
def calculate_P(ai, aj):
    """calculate P(ai > aj)
    """
    if ((ai[1] - ai[0]) + (aj[1] - aj[0])) == 0:
        return 1
    return min(max((ai[1] - aj[0]) / ((ai[1] - ai[0]) + (aj[1] - aj[0])), 0), 1)


1

In [ ]:
import numpy as np

def calculate_P_mtx(a):
    size_p = len(a)
    P_mtx = np.zeros([size_p,size_p])
    for j in range(size_p):
        for k in range(size_p):
            value = 0
            for i in range(size_p):
                value += calculate_P(a[i][j], a[i][k])
            P_mtx[j, k] = value / size_p
    return P_mtx

def calculate_w(mtx):
    sum_all = 0
    size_p = len(mtx)
    for i in range(size_p):
        for j in range(size_p):
            sum_all += mtx[i][j]
    sum_all = sum_all - size_p
    wj = []
    for j in range(size_p):
        sum_temp = 0
        for k in range(size_p):
            if k != j:
                sum_temp += mtx[j][k]
        wj.append(sum_temp)
    return wj/sum_all

In [ ]:
mtx

[[(1.0, 1.0, 1.0), (7.2, 8.2, 9.2), (0.4, 1.4, 2.4), (0.8, 1.8, 2.8)],
 [(7.2, 8.2, 9.2), (1.0, 1.0, 1.0), (0.8, 1.8, 2.8), (1.6, 2.6, 3.6)],
 [(0.0, 1.0, 2.0), (0.4, 1.4, 2.4), (1.0, 1.0, 1.0), (4.0, 5.0, 6.0)],
 [(0.0, 1.0, 2.0), (0.2, 1.2, 2.2), (0.8, 1.8, 2.8), (1.0, 1.0, 1.0)]]

In [ ]:
calculate_P(mtx[2][0], mtx[2][0])

1

In [ ]:
P_mtx = calculate_P_mtx(mtx)

In [ ]:
P_mtx

array([[0.625, 0.425, 0.425, 0.3  ],
       [0.575, 0.625, 0.45 , 0.3  ],
       [0.575, 0.55 , 0.625, 0.3  ],
       [0.7  , 0.7  , 0.7  , 0.625]])

In [ ]:
calculate_w(P_mtx)

array([0.47647059, 0.46470588, 0.47058824, 0.52941176])

In [ ]:
mtx_inv = []
for i in range(len(mtx)):
    inv_row = []
    for j in range(len(mtx[0])):
        inv_row.append(mtx[j][i])
    mtx_inv.append(inv_row)
mtx_inv

[[(1.0, 1.0, 1.0), (7.2, 8.2, 9.2), (0.0, 1.0, 2.0), (0.0, 1.0, 2.0)],
 [(7.2, 8.2, 9.2), (1.0, 1.0, 1.0), (0.4, 1.4, 2.4), (0.2, 1.2, 2.2)],
 [(0.4, 1.4, 2.4), (0.8, 1.8, 2.8), (1.0, 1.0, 1.0), (0.8, 1.8, 2.8)],
 [(0.8, 1.8, 2.8), (1.6, 2.6, 3.6), (4.0, 5.0, 6.0), (1.0, 1.0, 1.0)]]

In [ ]:
P_mtx_inv = calculate_P_mtx(mtx_inv)
P_mtx_inv

array([[1.   , 0.6  , 0.75 , 0.95 ],
       [0.75 , 1.   , 0.65 , 0.95 ],
       [0.65 , 0.55 , 1.   , 0.8  ],
       [0.55 , 0.5  , 0.725, 1.   ]])

In [ ]:
calculate_w(P_mtx_inv)

array([0.27299703, 0.27893175, 0.23738872, 0.21068249])

In [ ]:
sum_all = 0
size_p = 4
for i in range(size_p):
    for j in range(size_p):
        sum_all += P_mtx[i][j]
sum_all = sum_all - size_p

In [ ]:
sum_all

8.25

In [ ]:
wj = []
for j in range(size_p):
    sum_temp = 0
    for k in range(size_p):
        if k != j:
            sum_temp += P_mtx[j][k]
    wj.append(sum_temp)
wj/sum_all

array([0.24545455, 0.23939394, 0.24242424, 0.27272727])

### end

In [ ]:
p1 = []
i = 0
with open("data1.txt", 'r') as f:
    data_1 = f.readlines()

    while i < len(data_1):
        p1_row = []
        for j in range(len(data_1)):
            p1_row.append(float(data_1[i].split(" ")[j]))
        i += 1
        p1.append(p1_row)
        p1_row = []
p1 = np.array(p1)

In [ ]:
p1

array([[0.5  , 0.488, 0.513, 0.516, 0.505, 0.518],
       [0.512, 0.5  , 0.488, 0.493, 0.508, 0.465],
       [0.487, 0.512, 0.5  , 0.501, 0.504, 0.462],
       [0.484, 0.507, 0.499, 0.5  , 0.51 , 0.507],
       [0.495, 0.492, 0.496, 0.49 , 0.5  , 0.481],
       [0.482, 0.535, 0.538, 0.493, 0.519, 0.5  ]])

In [ ]:
calculate_w(p1)

array([0.21166667, 0.2055    , 0.2055    , 0.20891667, 0.2045    ,
       0.21391667])

In [ ]:
sumx_1 = 0
for a in d1:
    for data in a:
        sumx_1 += data
sumx = round(sumx, 2)
sum_ai_1 = []
for a in d1:
    sum_ai_1.append(round(sum(a), 2))
D1 = []
for i in range(6):
    D1.append(round(sum_ai[i]/ sumx_1, 6))
D1

[0.135845, 0.168039, 0.173316, 0.284252, 0.120752, 0.117796]

In [ ]:
sumx_2 = 0
for a in d2:
    for data in a:
        sumx_2 += data
sum_ai_2 = []
for a in d2:
    sum_ai_2.append(round(sum(a), 2))
D2 = []
for i in range(6):
    D2.append(round(sum_ai_2[i]/ sumx_2, 6))
D2

[0.143258, 0.167709, 0.171717, 0.255972, 0.131794, 0.129549]

In [ ]:
sum_3 = 0
for a in d3:
    for data in a:
        sum_3 += data
sum_ai_3 = []
for a in d3:
    sum_ai_3.append(round(sum(a), 2))
D3 = []
for i in range(6):
    D3.append(round(sum_ai_3[i]/ sum_3, 6))
D3

[0.147796, 0.167507, 0.170738, 0.238658, 0.138555, 0.136746]

In [ ]:
print(D1)
print(D2)
print(D3)

[0.154, 0.19, 0.196, 0.322, 0.137, 0.134]
[0.143, 0.168, 0.172, 0.256, 0.132, 0.13]
[0.148, 0.168, 0.171, 0.239, 0.139, 0.137]


In [ ]:
D = []
for i in range(6):
    D.append((D1[i], D2[i], D3[i]))
D

[(0.135845, 0.143258, 0.147796),
 (0.168039, 0.167709, 0.167507),
 (0.173316, 0.171717, 0.170738),
 (0.284252, 0.255972, 0.238658),
 (0.120752, 0.131794, 0.138555),
 (0.117796, 0.129549, 0.136746)]

In [ ]:
def calculate_P(ai, aj):
    """calculate P(ai > aj)
    """
    if ai[1] >= aj[1]:
        return 1

    if ai[1] < aj[1] and ai[2] > aj[0]:
        return (aj[0] - ai[2]) / ((ai[1] - ai[2]) - (aj[1] - aj[0]))
    else:
        return 0



In [ ]:
def calculate_P_ai_min(a, i):
    """calculate P(ai > a1, a2, ... ak)
    """
    len_a = len(a)
    P = []
    for j in range(len_a):
        value = calculate_P(a[i], a[j])
        print(f"{j} times: {value}")
        P.append(value)

    return min(P)


In [ ]:
d1

[[1.0, 1.58, 2.14, 6.51, 0.82, 0.82],
 [0.2, 1.0, 7.36, 7.36, 0.0, 0.0],
 [0.7, 7.36, 1.0, 7.36, 0.0, 0.0],
 [7.31, 7.36, 7.36, 1.0, 1.95, 1.95],
 [0.82, 0.0, 0.0, 1.95, 1.0, 7.67],
 [0.82, 0.0, 0.0, 1.67, 7.67, 1.0]]

In [ ]:
or_mtx = []
for j in range(6):
    row = []
    for i in range(6):

        e1 = d1[i][j]
        e2 = d2[i][j]
        e3 = d3[i][j]
        row.append((e1, e2, e3))
    or_mtx.append(row)


or_mtx

(7.36, 8.36, 9.36)

In [ ]:
import numpy as np

def calculate_P_mtx(a):
    size_p = len(a)
    P_mtx = np.zeros([size_p,size_p])
    for j in range(size_p):
        for k in range(size_p):
            value = 0
            for i in range(size_p):
                value += calculate_P(a[i][j], a[i][k])
            P_mtx[j, k] = value / size_p
    return P_mtx

In [ ]:
P_mtx = calculate_P_mtx(or_mtx)

In [ ]:
P_mtx

array([[1.        , 0.72916667, 0.64583333, 0.31166667, 0.69666667,
        0.69666667],
       [0.69666667, 1.        , 0.79166667, 0.34166667, 0.78166667,
        0.78166667],
       [0.69666667, 0.83333333, 1.        , 0.34166667, 0.82333333,
        0.82333333],
       [0.83333333, 0.83333333, 0.83333333, 1.        , 0.66666667,
        0.66666667],
       [0.39833333, 0.66666667, 0.66666667, 0.33333333, 1.        ,
        0.83333333],
       [0.39833333, 0.66666667, 0.66666667, 0.33333333, 0.81      ,
        1.        ]])

## calculate D

In [ ]:
sum_all = 0
for i in range(6):
    for j in range(6):
        sum_all += P_mtx[i][j]
sum_all = sum_all - 6

In [ ]:
wj = []
for j in range(6):
    sum_temp = 0
    for k in range(6):
        if k != j:
            sum_temp += P_mtx[j][k]
    wj.append(sum_temp)
wj/sum_all

array([0.15715622, 0.17314397, 0.17952207, 0.19559486, 0.14788673,
       0.14669615])

In [ ]:
sum(wj/ sum_all)

0.9999999999999996

In [ ]:
calculate_P_ai_min(D, 0)

In [ ]:
d1[1][0]

0.2

In [ ]:
def calculate_ai(d1, d2, d3, i):
    e1 = calculate_element_ai(d1, i)
    e2 = calculate_element_ai(d2, i)
    e3 = calculate_element_ai(d3, i)
    return (e1, e2, e3)


In [ ]:
def calculate_element_ai(d, i):
    sum_ai = 0
    for j in range(6):
        sum_ai += d[j][i]
    return sum_ai

In [ ]:
A = []
for i in range(6):
    A.append(calculate_ai(d1, d2, d3, i))
A

[(10.85, 15.850000000000001, 20.85),
 (17.3, 22.299999999999997, 27.299999999999997),
 (17.86, 22.86, 27.86),
 (25.85, 30.849999999999994, 35.85),
 (11.44, 16.44, 21.439999999999998),
 (11.44, 16.44, 21.439999999999998)]

In [ ]:
C = []
for i in range(6):
    c1 = A[i][0] * D[i][0]
    c2 = A[i][1] * D[i][1]
    c3 = A[i][2] * D[i][2]
    C.append((c1, c2, c3))
C

[(1.4739182499999999, 2.2706393, 3.0815466000000002),
 (2.9070747, 3.7399106999999994, 4.5729410999999995),
 (3.09542376, 3.92545062, 4.75676068),
 (7.347914200000001, 7.896736199999998, 8.5558893),
 (1.38140288, 2.16669336, 2.9706192),
 (1.3475862399999998, 2.12978556, 2.9318342399999997)]

In [ ]:
calculate_P_ai_min(C, 0)

0 times: 1
1 times: 0.10614303340430369
2 times: -0.008456865813555757
3 times: -3.137659532673165
4 times: 1
5 times: 1


-3.137659532673165

In [ ]:
len(A)

6

[(10.85, 15.850000000000001, 20.85), (17.3, 22.299999999999997, 27.299999999999997), (17.86, 22.86, 27.86), (25.85, 30.849999999999994, 35.85), (11.44, 16.44, 21.439999999999998), (11.44, 16.44, 21.439999999999998)]


[(0.135845, 0.143258, 0.147796),
 (0.168039, 0.167709, 0.167507),
 (0.173316, 0.171717, 0.170738),
 (0.284252, 0.255972, 0.238658),
 (0.120752, 0.131794, 0.138555),
 (0.117796, 0.129549, 0.136746)]

In [ ]:
aa = [0.3*0.143, 0.145 * 0.167709, 0.2 * 0.171, ]

0.024317804999999998